// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0fI_SDD0jr3ZgTl8VXAka-uC-C6RJB0',
    appId: '1:701936380417:web:6f2a56454d0ac074f36e00',
    messagingSenderId: '701936380417',
    projectId: 'mytake-a7a56',
    authDomain: 'mytake-a7a56.firebaseapp.com',
    storageBucket: 'mytake-a7a56.appspot.com',
    measurementId: 'G-GTKM50RSLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuPTASgcgg7Qheq46fBexGoirMPZIkhuE',
    appId: '1:701936380417:android:932dcf2e006fb8b2f36e00',
    messagingSenderId: '701936380417',
    projectId: 'mytake-a7a56',
    storageBucket: 'mytake-a7a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtvFvjDQ8FhYJEpT53PxJWi0tAEn-7-cA',
    appId: '1:701936380417:ios:d2874e43676cf1a1f36e00',
    messagingSenderId: '701936380417',
    projectId: 'mytake-a7a56',
    storageBucket: 'mytake-a7a56.appspot.com',
    iosClientId: '701936380417-r82mtcvls450qdmeaj5k2gfl01m5mgpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytakeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtvFvjDQ8FhYJEpT53PxJWi0tAEn-7-cA',
    appId: '1:701936380417:ios:d2874e43676cf1a1f36e00',
    messagingSenderId: '701936380417',
    projectId: 'mytake-a7a56',
    storageBucket: 'mytake-a7a56.appspot.com',
    iosClientId: '701936380417-r82mtcvls450qdmeaj5k2gfl01m5mgpn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytakeapp',
  );
}
